pipeline {
    agent {
        docker {
            image 'python:3.7.13-slim'
            args '--user root'
        }
    }

    stages {
        stage('build') {
            when {
                changeset "**/vote/**"
            }
            steps {
                echo 'Starting build step'
                echo 'Compiling vote app'
                dir('vote'){
                    sh 'pip3 install -i requirements.txt'
                }
                echo 'Finish build step'
                sleep 5
            }
        }
        stage('test') {
            when {
                changeset "**/vote/**"
            }
            steps {
                echo 'Starting test step'
                echo 'Running Unit Test on vote app'
                dir('vote'){
                    sh 'nosetest -v'
                }
                echo 'Finish test step'
                sleep 5
            }
        }
    }
    post {
        always{
            echo 'This pipeline finish'
        }
    }
}
